SHOW DATABASES;

DROP DATABASE IF EXISTS db_test;

CREATE DATABASE IF NOT EXISTS db_test DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

CREATE USER IF NOT EXISTS 'yanrk'@'%' IDENTIFIED BY '123456';
GRANT SELECT, UPDATE, INSERT, DELETE ON db_test.* TO 'yanrk'@'%';
FLUSH PRIVILEGES;

USE db_test;

CREATE TABLE IF NOT EXISTS `t_type_check` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `b` INT NOT NULL,
    `i8` INT NOT NULL,
    `u8` INT NOT NULL,
    `i16` INT NOT NULL,
    `u16` INT NOT NULL,
    `i32` INT NOT NULL,
    `u32` INT NOT NULL,
    `i64` BIGINT NOT NULL,
    `u64` BIGINT NOT NULL,
    `f` FLOAT NOT NULL,
    `d` DOUBLE NOT NULL,
    `s` VARCHAR(64) NOT NULL,
    PRIMARY KEY ( `id` )
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `t_conf_abc` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `a` BIGINT NOT NULL,
    `b` INT NOT NULL,
    `c` INT NOT NULL,
    PRIMARY KEY ( `id` )
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `t_data_xyz` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `x` VARCHAR(64) NOT NULL,
    `y` INT NOT NULL,
    `z` DOUBLE NOT NULL,
    PRIMARY KEY ( `id` )
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci;

SHOW TABLES;

DESCRIBE t_type_check;
DESCRIBE t_conf_abc;
DESCRIBE t_data_xyz;

DELETE FROM t_type_check;
DELETE FROM t_conf_abc;
DELETE FROM t_data_xyz;
